# Dockerfile-django
FROM python:3.11
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the current directory contents into the container at /code
COPY . /code/

## Collect static files
#RUN python manage.py collectstatic --noinput

# Command to run the Django server
#CMD ["gunicorn", "--bind", "0.0.0.0:8000", "revving.wsgi:application"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

#
#
## Use an official Python runtime as a parent image
#
#FROM python:3.12-slim
#
## Set environment varibles
#ENV PYTHONDONTWRITEBYTECODE 1
#ENV PYTHONUNBUFFERED 1
#
## Set work directory
#WORKDIR /code
#
## Install dependencies
#COPY requirements.txt /code/
#RUN pip install --upgrade pip && pip install -r requirements.txt
#
## Copy project
#COPY . /code/
#
### Collect static files
##RUN python manage.py collectstatic --noinput
#
## Make port 8000 available to the world outside this container
#EXPOSE 8000
#
## Command to run the Django development server
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
#
## Note: For production, consider using gunicorn or another WSGI server instead of the Django development server
