version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: revving
      POSTGRES_USER: colinkingswood
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  migrate:
    build:
      context: .  # Assuming the Dockerfile is in the root directory
      dockerfile: Dockerfile-django  # Specifically using the development
    command: python manage.py migrate
    volumes:
      - .:/app
    depends_on:
      - db

  tests:
    build:
      context: .  # Assuming the Dockerfile is in the root directory
      dockerfile: Dockerfile-django  # Specifically using the development
    command: python manage.py test
    volumes:
      - .:/app
    depends_on:
      - db




volumes:
  postgres_data:

