version: '3'

services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: yourdbname
#      POSTGRES_USER: yourdbuser
#      POSTGRES_PASSWORD: yourdbpassword
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
#      - db
      - redis

  celery:
    build: .
    command: celery -A revving worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine

volumes:
  postgres_data:
