# Dockerfile-django
FROM python:3.11
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the current directory contents into the container at /code
COPY . /code/

## Collect static files
#RUN python manage.py collectstatic --noinput

# Command to run the Django server
#CMD ["gunicorn", "--bind", "0.0.0.0:8000", "revving.wsgi:application"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
