# Generated by Django 5.0.1 on 2024-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_number', models.IntegerField(unique=True)),
                ('value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('haircut_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('daily_fee_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('currency', models.CharField(max_length=4)),
                ('revenue_source', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('payment_duration', models.PositiveSmallIntegerField(verbose_name='expected payment duration')),
            ],
        ),
    ]
